import localFont from "next/font/local";
import "./globals.css";
import MyComponents from "./components/MyComponent";
import Header from "./components/Header";
import Footer from"./components/Footer";
import Hero from "./components/Hero";
import ProductsCardfile from "./components/ProductsCardfile";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      

        <MyComponents />
        <Header />
        <Hero />
        <herotwo />
        <ProductsCardfile />
        {children}
        <Footer />
      </body>
    </html>
  );
}
